# Usage of double wildcards and variables

samples = ["DOLPHINS", "WHALES"]
windows = [512, 1024, 2048, 4096]

rule all:
    input: expand("{name}_{ws}.png", name=samples, ws=windows)

rule spectrogram:
    input: "{dataset}.wav"
    output: "{dataset}_{window}.png"
    shell:
        "python spectrogram.py {input} {wildcards.window}"

rule clean:
    shell: "rm -f DOLPHINS*png WHALES*png WHALES.wav DOLPHINS.wav"

rule copy:
    output: "{dataset}.wav"
    shell: "cp ../data/{wildcards.dataset}.wav ."
